# Generated by Django 5.2.3 on 2025-06-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code')),
                ('supplier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier')),
                ('supplier_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Supplier Code')),
                ('name_en', models.CharField(max_length=200, verbose_name='Item Title (EN)')),
                ('name_lt', models.CharField(blank=True, max_length=200, null=True, verbose_name='Item Title (LT)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (EN)')),
                ('description_lt', models.TextField(blank=True, null=True, verbose_name='Description (LT)')),
                ('price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Price')),
                ('cost', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Prime Cost')),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='VAT')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Weight (kg)')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manufacturer')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Product Image File')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Product Image URL')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
