# Generated by Django 5.2.3 on 2025-06-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_manufacturingqueueitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pouch_tip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pouch Tip'),
        ),
    ]
