# Generated by Django 5.2.3 on 2025-06-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_product_pouch_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingqueueitem',
            name='box_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingqueueitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingqueueitem',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingqueueitem',
            name='lid_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingqueueitem',
            name='lot_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingqueueitem',
            name='order_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingqueueitem',
            name='pouch_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingqueueitem',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingqueueitem',
            name='spray_function',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manufacturingqueueitem',
            name='strength',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
