# Generated by Django 5.2.3 on 2025-06-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_manufacturingqueueitem_box_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pouch_length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pouch Length (mm)'),
        ),
    ]
