# Generated by Django 5.2.3 on 2025-06-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_product_pouch_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_lt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_lt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pouch_length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pouch_tip',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default='DEFAULT_CODE', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
