# Generated by Django 5.2.3 on 2025-06-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_alter_product_options_remove_product_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Prime Cost'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_lt',
            field=models.TextField(blank=True, null=True, verbose_name='Description (LT)'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Product Image File'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_lt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Item Title (LT)'),
        ),
        migrations.AddField(
            model_name='product',
            name='pouch_length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pouch Length (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='pouch_tip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pouch Tip'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Supplier Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='VAT'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Product Image URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, verbose_name='Item Title (EN)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier'),
        ),
    ]
