# Generated by Django 5.2.3 on 2025-06-23 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0010_remove_product_image_file_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producthistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Product History', 'verbose_name_plural': 'Product Histories'},
        ),
        migrations.AddField(
            model_name='producthistory',
            name='lot_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='manufacturing_queue_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory.manufacturingqueueitem'),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='quantity_produced',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='change_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('manufacturing_completed', 'Manufacturing Completed')], max_length=30),
        ),
    ]
